# see: https://pre-commit.com/hooks.html

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-case-conflict
      - id: check-ast
      - id: check-json
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: testdata
      - id: requirements-txt-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace
      - id: check-added-large-files

  -   repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.10.1
      hooks:
      - id: isort

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        files: ^svc/
        args: [--max-line-length=119, --ignore=E731]

  -   repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
      - id: black
